First commit
GLexx909/simpler pull request #1
Opened 2018-11-09 10:16 UTC by GLexx909

No comments

2018-11-10 06:41 UTC, iBublik requested changes

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/application.rb
> +        [404, { 'Content-Type' => 'text/plain' }, ['Template not found. 404']]
Лучше сразу верни этот результат и выйди из метода, если роут не найден. Это позволит сделать основное тело метода без лишней вложенности

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/controller.rb
> +    def method_definition(data)
Зачем это в отдельный метод? У него непонятное название, а метод `render` в итоге просто его вызывает и не содержит никакой другой логики

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.params[:id] = id
Параметры должны уметь не только с id работать, а с любыми указанными в роутах именами (например `/tests/:test_id/questions:id` => `params[:test_id], parmas[:id]`)

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.params[:id] = id
Не нужно мутировать параметры запроса, пускай там лежит только то что пришло из браузера. Параметры, которые парсит роутер лучше сложить в env, тогда не придется логику в контроллере дублировать

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/controller.rb
> +      {id: id}
Параметры контроллера должны давать доступ ко всем входящим параметра - из строки запроса, из формы

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/router.rb
> +      @routes.find { |route| route.match?(method, path) } || false # Может дефолтный маршрут создать? И вьюху соответственно.
Не надо дефолтного маршрута, у тебя тогда любой запрос будет обрабатываться. Если обратились к несуществующему url-у, то должен 404 прийти в ответ, иначе пользователь не поймет что ввел неверный адрес

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/router.rb
> +      @routes.find { |route| route.match?(method, path) } || false # Может дефолтный маршрут создать? И вьюху соответственно.
И false не надо возвращать, nil логически эквивалентен false

2018-11-10 06:41 UTC, iBublik commented on lib/simpler/router/route.rb
> +        if path_array.last.to_i > 0
Параметр может быть не последним и вовсе не обязан быть числом

2018-11-10 06:41 UTC, iBublik commented on log/app.log
> +I, [2018-11-09T12:40:39.733528 #20600]  INFO -- :
Убери лог из репозитория

2018-11-10 06:41 UTC, iBublik commented on middleware/logger.rb
> +    "
Для многострочников используй HEREDOC или `%(Request: ...)`

2018-11-11 13:43 UTC, GLexx909 commented on lib/simpler/application.rb
> +      [404, { 'Content-Type' => 'text/plain' }, ['Template not found. 404']] unless route
return

2018-11-11 18:14 UTC, iBublik requested changes

2018-11-11 18:14 UTC, iBublik commented on lib/simpler/application.rb
> +      return [404, { 'Content-Type' => 'text/plain' }, ['Template not found. 404']] unless route
Можно избежать отрицания (его мозгу сложнее парсить) через `if route.nil?`

2018-11-11 18:14 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['REQUEST_PARAMS'] = {}
Ты сейчас задачу роутера решаешь в контроллере. Роутер должен распарсить параметры в соответствии с текущим маршрутом и сложить их в env. А контроллер просто соберет параметры из разных мест воедино

2018-11-11 18:14 UTC, iBublik commented on lib/simpler/controller.rb
> +      primary_key = Simpler.application.db[@name.to_sym].columns[0]
С БД тут вообще никакой связи не должно быть. Опирайся на особый формат маршрута (налаиче двоеточия `:`)

2018-11-12 18:37 UTC, iBublik requested changes

2018-11-12 18:37 UTC, iBublik commented on middleware/logger.rb
> +    controller_name = (controller.name if controller)  || 'Bad request'
`controller&.name || 'Bad request'`

2018-11-12 18:37 UTC, iBublik commented on lib/simpler/router/route.rb
> +        if path_array.last.to_i > 0
> Параметр может быть не последним и вовсе не обязан быть числом

Ты продолжаешь зашиваться на специфичную структуру url-а

2018-11-12 18:37 UTC, iBublik commented on lib/simpler/router/route.rb
> +          path_array << ':id'
Имя параметра не обязано быть `:id`

2018-11-12 18:37 UTC, iBublik commented on lib/simpler/router.rb
> +      primary_key = Simpler.application.db[table_name.to_sym].columns[0]
Зачем тебе вообще как-то к структуре БД привязываться? Роуты вообще не должны быть никак связаны с этим

2018-11-12 18:37 UTC, iBublik commented on lib/simpler/router.rb
> +        env['REQUEST_PARAMS'][primary_key]=path_arr[index+1].to_i if (element.to_i==0 && path_arr[index+1].to_i>0)
Нельзя полагаться на `to_i`. Мне показалось, что ты таким образом проверяешь является ли элемент числом - это сосвсем неочевидно. Плюс я уже говорил, что id могут быть строковыми (UUID), но это вообще неважно. Нужно мапить любое значение, которое находится в нужной позиции между `/`. Например, если описан роут `/tests/:id` и приходит запрос `/tests/qwe`, то это должно корректно смапиться, а в контроллере `params[:id]` должно вернуть `qwe`. Полагайся на символ двоеточия `:` - в нашем роутере это символ захвата параметра

2018-11-13 19:57 UTC, iBublik requested changes

2018-11-13 19:57 UTC, iBublik commented on lib/simpler/router.rb
> +      env['REQUEST_PARAMS'] = {}
Данные, которые созданы приложением, лучше помечать, чтоб было понятно откуда они взялись в env. По всему приложению это делается через префикс simpler, тут лучше также сделать - `env['simpler.route_params']`

2018-11-13 19:57 UTC, iBublik commented on lib/simpler/router.rb
> +      params = {}
Зачем какой-то промежуточный хэш создавать, почему сразу не писать в env?

2018-11-13 19:57 UTC, iBublik commented on lib/simpler/router.rb
> +        env['REQUEST_PARAMS'][key] = value.to_i
Еще раз, значения вовсе не обязаны быть числами

2018-11-13 19:57 UTC, iBublik commented on middleware/logger.rb
> +    params = env['REQUEST_PARAMS'] || '{}'
Тут нужны все параметры, включая параметры POST-запроса и роут-параметры. Подсказка - у тебя есть контроллер, а он как раз может вернуть все параметры

2018-11-13 19:57 UTC, iBublik commented on lib/simpler/router/route.rb
> +      def path_detect(path)
Сделай метод приватным

2018-11-13 19:57 UTC, iBublik commented on lib/simpler/router/route.rb
> +            path_arr[index] = '.*'
В чем суть `map`-а, если ты просто изменяешь исходный массив? `map` создан для построения новой коллекции из существующей, используй это.

2018-11-14 07:02 UTC, GLexx909 commented on middleware/logger.rb
> +    params = env['REQUEST_PARAMS'] || '{}'
Эта строка в моём контроллере что делает? `@request.env['REQUEST_PARAMS'].merge!(@request.params)`

2018-11-14 07:15 UTC, GLexx909 commented on lib/simpler/router.rb
> +        env['REQUEST_PARAMS'][key] = value.to_i
Иначе `params[:id]` из хэша `{:id => '2'}` вытягивает строку `'2'` и не знает, что с ней делать.

2018-11-14 18:36 UTC, iBublik requested changes

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/application.rb
> +      return [404, { 'Content-Type' => 'text/plain' }, ['Template not found. 404']] if route.nil?
Массив можно вынести в отдельный метод (или даже константу) `not_found_response`. Так код будет проще понимать

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/controller.rb
> +      body = @request.env['simpler.render_plain'] || render_body
Проверку стоит поместить в метод, это как раз его работа

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.route_params'].merge!(@request.params) #  @request.params вернёт hash всех GET & POST parameters?
Зачем тут `merge!`? Так ты мутировал хэш, лежащий в `simpler.route_params`. Если в другой части фреймворка потребуется получить только параметры маршрута, сделать это будет невозможно

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.render_plain'] = value
Здесь должен быть другое значение заголовка Content-Type. Сейчас отдается text/html, что не соответствует действительности

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/router.rb
> +      if route_found
Сразу выходи из метода, если маршрут не найден

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/router.rb
> +      @env_path_arr = path.split('/')
Зачем это делать инстанс-перемнной?

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/router.rb
> +          env['simpler.route_params'][part.delete(':').to_sym] = index if part.match?(':')
По сути ничего не поменялось. Зачем писать индекс, когда можно сразу значение записывать?

2018-11-14 18:36 UTC, iBublik commented on lib/simpler/router.rb
> +          env['simpler.route_params'][key] = value.match?(/[^\d]/) ? value : value.to_i
Не нужно делать преобразование типов параметров. Это вообще не задача роутера, если очень надо, то делай это на другом уровне. В рельсах этим занимаются модели, в Grape/Hanami описывается схема параметров на уровне контроллеров, которая и делает преобразование.

2018-11-14 18:36 UTC, iBublik commented on middleware/logger.rb
> +    params = env['simpler.route_params'] || '{}'
Нельзя полагаться на то, что контроллер мутировал это значение, докинув все параметры в параметры маршрута. Получается, логгер знает о внутреннем устройстве другого компонента

2018-11-15 18:21 UTC, iBublik requested changes

2018-11-15 18:21 UTC, iBublik commented on lib/simpler/router.rb
> +      route_found.path.split('/').map.with_index do |part, index|
`map` можно заменить на `each`, с точки зрения назначения методов это будет правильнее

2018-11-15 18:21 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.request_params'] = @request.params
Зачем еще что-то в env писать? Это же нигде не используется

2018-11-15 18:21 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.all_params'].merge!(@request.params)
Это все лишнее, у тебя из логгера доступен инстанс контроллера. А у контроллера есть метод, возвращающий _все_ параметры. Вот и используй его

2018-11-15 18:21 UTC, iBublik commented on lib/simpler/controller.rb
> +      @request.env['simpler.route_params']
Изначальная задача метода - вернуть все параметры, а не только параметры маршрута

2018-11-15 18:21 UTC, iBublik commented on lib/simpler/router/route.rb
> +        @method == method && same_length?(path) && (/^#{path_init}$/).match?(path) && path.match?(/^#{path_init}/)
А зачем дважды делать `match?`?

2018-11-16 19:49 UTC, iBublik approved these changes

2018-11-16 19:49 UTC, iBublik commented on lib/simpler/controller.rb
> +      params = {}.merge!(@request.params)
Что-то странное тут происходит. Почему не `@request.params.merge(@request.env['simpler.route_params'])`?

2018-11-16 19:49 UTC, iBublik commented on middleware/logger.rb
> +    params = {}.merge!(env['simpler.route_params'])
В переменной `controller` экземпляр контроллера. У него есть метод с точно такой же логикой, но ты ее зачем-то дублируешь. А можно просто `controller.&params || {}`

2018-11-17 09:19 UTC, merged